"""
Configuration constants for NCAA basketball data pipeline.
"""
from pathlib import Path

# ===== Directory Structure =====
# Note: These paths assume config.py is in ncaa_pipeline/ directory
BASE_DIR = Path(__file__).parent.parent.parent.parent 

OUT_DIR = BASE_DIR / "data" / "cleaned"
BET_DIR = BASE_DIR / "data" / "historical" / "betting_historical"
RAW_DIR = BASE_DIR / "data" / "historical" / "raw_historical"

# Daily rating feeds (Torvik / Bart Torvik)
TORVIK_DAILY_PATH = RAW_DIR / "torvik_daily.csv"
TORVIK_FEATURE_COLS = ["rank", "barthag", "adj_o", "adj_d"]

# ===== Processing Years =====
YEAR_LIST = ["2019", "2020", "2021", "2022", "2023", "2024", "2025"]

# ===== Normalization Configuration =====
# Choose one of: None, "season", "expanding"
NORMALIZE_MODE = "season"


# ===== Betting Line Column Mappings =====
BET_COLS_MAP = {
    "Date": "Date",
    "Team": "bet_Team",
    "Opponent": "bet_Opponent",
    "Location": "bet_Location",
    "Score": "bet_Score",
    "Spread": "bet_spread",
    "ATS Margin": "bet_ats_margin",
    "Total (O/U)": "bet_total",
    "Combined": "bet_combined",
    "O/U Margin": "bet_ou_margin",
    "Moneyline": "bet_moneyline",
    "MOV": "bet_mov",
}

# Columns that need to be flipped when swapping team/opponent perspective
DIRECTIONAL_BET_COLS = ["bet_spread", "bet_ats_margin", "bet_mov"]

# Columns that apply to the game as a whole (not directional)
GAME_LEVEL_BET_COLS = ["bet_total", "bet_combined", "bet_ou_margin"]

# Canonical betting columns expected across all seasons
CANONICAL_BET_COLS = [
    "bet_spread",
    "bet_ats_margin",
    "bet_mov",
    "bet_total",
    "bet_combined",
    "bet_ou_margin",
    "moneyline_a",
    "moneyline_b",
]

# ===== Path Helpers =====
def raw_path_for(year: str) -> str:
    """Return path to raw game logs CSV for a given year."""
    return str(RAW_DIR / f"d1_mens_basketball_{year}_gamelogs.csv")

def betting_path_for(year: str) -> Path:
    """Return path to betting lines CSV for a given year."""
    path_fixed = BET_DIR / f"{year}BettingLinesCBB_fixed.csv"
    return path_fixed if path_fixed.exists() else (BET_DIR / f"{year}BettingLinesCBB.csv")

# ===== Team Name Map =====
TEAM_ALIASES = {
    "ablchristian": "abilenechristian",
    "alabam": "alabamaam",
    "alabamast": "alabamastate",
    "albany": "albanyny",
    "alcornst": "alcornstate",
    "appstate": "appalachianstate",
    "arizonast": "arizonastate",
    "arkansasst": "arkansasstate",
    "arkpinebl": "arkansaspinebluff",
    "arlitrock": "arkansaslittlerock",
    "ballst": "ballstate",
    "bethcook": "bethunecookman",
    "boisest": "boisestate",
    "bostoncol": "bostoncollege",
    "bostonu": "bostonuniversity",
    "bowlinggrn": "bowlinggreenstate",
    "byu": "brighamyoung",
    "calbaptist": "californiabaptist",
    "calstnrdge": "calstatenorthridge",
    "centralark": "centralarkansas",
    "centralconn": "centralconnecticutstate",
    "centralmich": "centralmichigan",
    "charlsouth": "charlestonsouthern",
    "chicagost": "chicagostate",
    "clevelandst": "clevelandstate",
    "coastalcar": "coastalcarolina",
    "colcharlestn": "collegeofcharleston",
    "charleston": "collegeofcharleston",
    "coloradost": "coloradostate",
    "coppinst": "coppinstate",
    "purduefw": "ipfw",
    "iuindy": "iupui",
    "csbakersfld": "calstatebakersfield",
    "csfullerton": "calstatefullerton",
    "delawarest": "delawarestate",
    "detroit": "detroitmercy",
    "ecarolina": "eastcarolina",
    "ekentucky": "easternkentucky",
    "emichigan": "easternmichigan",
    "etennst": "easttennesseestate",
    "ewashingtn": "easternwashington",
    "fdickinson": "fairleighdickinson",
    "flaatlantic": "floridaatlantic",
    "flagulfcst": "floridagulfcoast",
    "floridaintl": "floridainternational",
    "floridast": "floridastate",
    "fresnost": "fresnostate",
    "gardwebb": "gardnerwebb",
    "gasouthern": "georgiasouthern",
    "gatech": "georgiatech",
    "geomason": "georgemason",
    "georgiast": "georgiastate",
    "georgiaso": "georgiasouthern",
    "gwashington": "georgewashington",
    "geowshgtn": "georgewashington",
    "houchristian": "houstonbaptist", 
    "hsnchristian": "houstonbaptist",
    "idahost": "idahostate",
    "illinoisst": "illinoisstate",
    "indianast": "indianastate",
    "iowast": "iowastate",
    "jacksonst": "jacksonstate",
    "jacksonvillest": "jacksonvillestate",
    "kansast": "kansasstate",
    "kentst": "kentstate",
    "louisianast": "louisianastate",
    "longbeachst": "longbeachstate",
    "missst": "mississippistate",
    "missvalst": "mississippivalleystate",
    "montst": "montanastate",
    "moreheadst": "moreheadstate",
    "ncstate": "northcarolinastate",
    "ndst": "northdakotastate",
    "nillinois": "northernillinois",
    "northernariz": "northernarizona",
    "northtexas": "northtexas",
    "oklahomast": "oklahomastate",
    "oregonst": "oregonstate",
    "pennst": "pennstate",
    "sacstate": "sacramentostate",
    "samhoustonst": "samhoustonstate",
    "sandiegost": "sandiegostate",
    "santarosa": "santaclara", 
    "semo": "southeastmissouristate",
    "sillinois": "southernillinois",
    "siue": "southernillinoisedwardsville",
    "southal": "southalabama",
    "southcarst": "southcarolinastate",
    "stjohns": "stjohnsny",
    "stjosephs": "saintjosephs",
    "stlouis": "saintlouis",
    "syr": "syracuse",
    "tennessest": "tennesseestate",
    "tenntec": "tennesseetech",
    "tnmartin": "tennesseemartin",
    "towsonst": "towson",
    "txamcc": "texasamcorpuschristi",
    "txsout": "texassouthern",
    "utahst": "utahstate",
    "valdosta": "valparaiso", 
    "washst": "washingtonstate",
    "westvirg": "westvirginia",
    "wrightst": "wrightstate",
    "youngstownst": "youngstownstate",
    "ucriverside": "californiariverside",
    "tnstate": "tennesseestate",
    "kennesawst": "kennesawstate",
    "sdakotast": "southdakotastate",
    "wmmary": "williammary",
    "ewashingtn": "easternwashington",
    "scupstate": "southcarolinaupstate",
    "eillinois": "easternillinois",
    "upenn": "pennsylvania",
    "scarolinast": "southcarolinastate",
    "geomason": "georgemason",
    "gramblingst": "grambling",
    "kansascity": "missourikansascity",
    "ucdavis": "californiadavis",
    "latech": "louisianatech",
    "lsu": "louisianastate",
    "marylandbc": "marylandbaltimorecounty",
    "marylandes": "marylandeasternshore",
    "masslowell": "massachusettslowell",
    "liu": "longislanduniversity",
    "ncasheville": "northcarolinaasheville",
    "ncgrnsboro": "northcarolinagreensboro",
    "ncat": "northcarolinaat",
    "nccentral": "northcarolinacentral",
    "ncwilmgton": "northcarolinawilmington",
    "semissouri": "southeastmissouristate",
    "siuedward": "southernillinoisedwardsville",
    "stfranny": "saintfrancispa",
    "sutah": "southernutah",
    "tntech": "tennesseetech",
    "txpanam": "texaspanamerican",
    "uab": "alabamabirmingham",
    "ucf": "centralflorida",
    "ucirvine": "californiairvine",
    "ucsb": "californiasantabarbara",
    "ucsd": "californiasandiego",
    "ulmonroe": "louisianamonroe",
    "umass": "massachusetts",
    "unlv": "nevadalasvegas",
    "usc": "southerncalifornia",
    "utsa": "texassanantonio",
    "vatech": "virginiatech",
    "vcu": "virginiacommonwealth",
    "vmi": "virginiamilitaryinstitute",
    "youngsst": "youngstownstate",
    "alabamam": "alabamaam",
    "geowshgtn": "georgewashington",
    "gramblingst": "grambling",
    "grdcanyon": "grandcanyon",
    "houstonbap": "houstonbaptist",
    "ilchicago": "illinoischicago",
    "incarword": "incarnateword",
    "jamesmad": "jamesmadison",
    "jksnvillest": "jacksonvillestate",
    "kansascity": "missourikansascity",
    "kansasst": "kansasstate",
    "kennesawst": "kennesawstate",
    "lgbeachst": "longbeachstate",
    "louisiana": "louisianalafayette",
    "loyolachi": "loyolail",
    "loyolamymt": "loyolamarymount",
    "mcneesest": "mcneesestate",
    "miami": "miamifl",
    "michiganst": "michiganstate",
    "middletenn": "middletennessee",
    "missourist": "missouristate",
    "missstate": "mississippistate",
    "montanast": "montanastate",
    "morganst": "morganstate",
    "mtstmarys": "mountstmarys",
    "murrayst": "murraystate",
    "nalabama": "northalabama",
    "narizona": "northernarizona",
    "ncarolina": "westerncarolina",
    "ncolorado": "northerncolorado",
    "ndakotast": "northdakotastate",
    "nebomaha": "nebraskaomaha",
    "nflorida": "northflorida",
    "nhampshire": "newhampshire",
    "nicholls": "nichollsstate",
    "niowa": "northerniowa",
    "nkentucky": "northernkentucky",
    "nmexstate": "newmexicostate",
    "norfolkst": "norfolkstate",
    "northeastrn": "northeastern",
    "nwstate": "weberstate",
    "ohiost": "ohiostate",
    "portlandst": "portlandstate",
    "robmorris": "robertmorris",
    "sacredhrt": "sacredheart",
    "salabama": "southalabama",
    "samhousst": "samhoustonstate",
    "sanjosest": "sanjosestate",
    "scarolina": "southcarolina",
    "scarstate": "kansasstate",
    "sdakotast": "southdakotastate",
    "selouisiana": "southeasternlouisiana",
    "sflorida": "southflorida",
    "smethodist": "southernmethodist",
    "smississippi": "southernmississippi",
    "southernmiss": "southernmississippi",
    "stbonavent": "stbonaventure",
    "stefaustin": "stephenfaustin",
    "stfranpa": "saintfrancispa",
    "stmarys": "saintmarysca",
    "stpeters": "saintpeters",
    "stthomas": "stthomasmn",
    "tarletonst": "tarletonstate",
    "texasst": "texasstate",
    "txarlington": "texasarlington",
    "txchristian": "texaschristian",
    "txelpaso": "texaselpaso",
    "txsouthern": "texassouthern",
    "washstate": "washingtonstate",
    "wcarolina": "westerncarolina",
    "weberst": "weberstate",
    "wichitast": "wichitastate",
    "wigrnbay": "greenbay",
    "willinois": "westernillinois",
    "wimilwkee": "milwaukee",
    "wkentucky": "westernkentucky",
    "wmichigan": "michiganstate",
    "wvirginia": "westvirginia",
    "arpinebluff": "arkansaspinebluff",
    "bethune": "bethunecookman",
    "bowlinggreen": "bowlinggreenstate",
    "carkansas": "centralarkansas",
    "cconnecticut": "centralconnecticutstate",
    "charlestonso": "charlestonsouthern",
    "cmichigan": "centralmichigan",
    "csbakersfield": "calstatebakersfield",
    "csnorthridge": "calstatenorthridge",
    "etennesseest": "easttennesseestate",
    "etexasam": "texasamcorpuschristi",
    "txamcom": "texasamcommerce",
    "ewashington": "easternwashington",
    "fgcu": "floridagulfcoast",
    "jmadison": "jamesmadison",
    "littlerock": "arkansaslittlerock",
    "mcneesestate": "mcneesestate",
    "mcneese": "mcneesestate",
    "penn": "pennsylvania",
    "samhouston": "samhoustonstate",
    "mississippist": "mississippistate",
    "missvalleyst": "mississippivalleystate",
    "ncgreensboro": "northcarolinagreensboro",
    "ncwilmington": "northcarolinawilmington",
    "ncarolina": "northcarolina",
    "newmexicost": "newmexicostate",
    "ntexas": "northtexas",
    "omaha": "nebraskaomaha",
    "queensny": "queenscollege",
    "queens": "queensnc",
    "sacramentost": "sacramentostate",
    "saintmarys"    : "saintmarysca",
    "samhoustonst": "samhoustonstate",
    "scarstate": "southcarolinastate",
    "semissourist": "southeastmissouristate",
    "sfaustin": "stephenfaustin",
    "sindiana": "southernindiana",
    "smu": "southernmethodist",
    "stfrancispa": "saintfrancispa",
    "tcu": "texaschristian",
    "tennesseest": "tennesseestate",
    "tenntech": "tennesseetech",
    "texasamcc": "texasamcommerce",
    "texasso": "texassouthern",
    "thecitadel": "citadel",
    "uconn": "connecticut",
    "umasslowell": "massachusettslowell",
    "umbc": "marylandbaltimorecounty",
    "utahtech": "dixiestate",
    "utarlington": "texasarlington",
    "utep": "texaselpaso",
    "utmartin": "tennesseemartin",
    "utriogrande": "texaspanamerican",
    "washingtonst": "washingtonstate",
    "wgeorgia": "westgeorgia",
    "nwstate": "northwesternstate",

}

TEAM_ALIASES_TWO = {
    "appalachianst": "appalachianstate",
    "sandiego": "californiasandiego",
    "ucsantabarbara": "californiasantabarbara",
    "ucriverside": "californiariverside",
    "ucirvine"  : "californiairvine",
    "centralconnecticut": "centralconnecticutstate",
    "dixiest": "dixiestate",
    "fiu": "floridainternational",
    "clevelandst": "clevelandstate",
    "fortwayne": "ipfw",
    "liubrooklyn": "longislanduniversity",
    "loyolachicago": "loyolail",
    "umkc": "missourikansascity",
    "nicholsst": "nichollsstate",
    "uncasheville": "northcarolinaasheville",
    "uncgreensboro": "northcarolinagreensboro",
    "northcarolinast": "northcarolinastate",
    "uncwilmington": "northcarolinawilmington",
    "northdakotast": "northdakotastate",
    "northwesternst": "northwesternstate",
    "southcarolinast": "southcarolinastate",
    "uscupstate": "southcarolinaupstate",
    "southdakotast": "southdakotastate",
    "siuedwardsville": "southernillinoisedwardsville",
    "utriograndevalley": "texaspanamerican",

}
