//
//  TeamNameFormatter.swift
//  SportsAppTest
//
//  Created by Trenton Roney on 11/3/25.
//

import Foundation

struct TeamNameFormatter {
    
    /// Formats a team name from Firebase format (lowercase) to display format
    /// Example: "charleston-southern" -> "Charleston Southern"
    /// - Parameter firebaseName: The team name in Firebase format (lowercase, possibly hyphenated)
    /// - Returns: The formatted team name for display
    static func formatTeamName(_ firebaseName: String) -> String {
        return teamMapping[firebaseName.uppercased()] ?? formatUnknownTeam(firebaseName)
    }
    
    /// Formats an unknown team name by converting hyphens to spaces and capitalizing words
    /// - Parameter name: The team name to format
    /// - Returns: The formatted team name
    private static func formatUnknownTeam(_ name: String) -> String {
        let formattedName = name.replacingOccurrences(of: "-", with: " ")
        return formattedName
            .split(separator: " ")
            .map { $0.prefix(1).uppercased() + $0.dropFirst().lowercased() }
            .joined(separator: " ")
    }
    
    /// Maps standardized team names between Firebase format (uppercased key) and display format (value)
    /// This comprehensive map ensures consistent naming across the app
    static let teamMapping: [String: String] = [
        // ACC
        "NORTH-CAROLINA": "North Carolina",
        "UNC": "North Carolina",
        "DUKE": "Duke",
        "VIRGINIA": "Virginia", 
        "UVA": "Virginia",
        "NC-STATE": "NC State", 
        "NCSTATE": "NC State",
        "NCSU": "NC State",
        "WAKE-FOREST": "Wake Forest",
        "WAKE": "Wake Forest",
        "CLEMSON": "Clemson",
        "FLORIDA-STATE": "Florida State",
        "FSU": "Florida State",
        "LOUISVILLE": "Louisville",
        "MIAMI": "Miami",
        "MIAMI-FL": "Miami",
        "PITTSBURGH": "Pittsburgh",
        "PITT": "Pittsburgh",
        "SYRACUSE": "Syracuse",
        "VIRGINIA-TECH": "Virginia Tech",
        "VT": "Virginia Tech",
        "BOSTON-COLLEGE": "Boston College",
        "BC": "Boston College",
        "GEORGIA-TECH": "Georgia Tech",
        "GT": "Georgia Tech",
        "NOTRE-DAME": "Notre Dame",
        
        // Big Ten
        "MICHIGAN": "Michigan",
        "OHIO-STATE": "Ohio State",
        "MICHIGAN-STATE": "Michigan State",
        "MSU": "Michigan State",
        "PENN-STATE": "Penn State",
        "INDIANA": "Indiana",
        "PURDUE": "Purdue",
        "ILLINOIS": "Illinois",
        "IOWA": "Iowa",
        "WISCONSIN": "Wisconsin",
        "MINNESOTA": "Minnesota",
        "NORTHWESTERN": "Northwestern",
        "NEBRASKA": "Nebraska",
        "MARYLAND": "Maryland",
        "RUTGERS": "Rutgers",
        
        // Big 12
        "KANSAS": "Kansas",
        "KU": "Kansas",
        "KANSAS-STATE": "Kansas State",
        "K-STATE": "Kansas State",
        "TEXAS": "Texas",
        "TEXAS-TECH": "Texas Tech",
        "TCU": "TCU",
        "BAYLOR": "Baylor",
        "OKLAHOMA": "Oklahoma",
        "OKLAHOMA-STATE": "Oklahoma State",
        "IOWA-STATE": "Iowa State",
        "WEST-VIRGINIA": "West Virginia",
        
        // SEC
        "KENTUCKY": "Kentucky",
        "UK": "Kentucky",
        "TENNESSEE": "Tennessee",
        "ALABAMA": "Alabama",
        "AUBURN": "Auburn",
        "FLORIDA": "Florida",
        "GEORGIA": "Georgia",
        "LSU": "LSU",
        "ARKANSAS": "Arkansas",
        "MISSISSIPPI-STATE": "Mississippi State",
        "MISSISSIPPI": "Ole Miss",
        "OLE-MISS": "Ole Miss",
        "MISSOURI": "Missouri",
        "SOUTH-CAROLINA": "South Carolina",
        "TEXAS-A&M": "Texas A&M",
        "VANDERBILT": "Vanderbilt",
        
        // Pac-12
        "ARIZONA": "Arizona",
        "UCLA": "UCLA",
        "USC": "USC",
        "SOUTHERN-CALIFORNIA": "USC",
        "OREGON": "Oregon",
        "WASHINGTON": "Washington",
        "STANFORD": "Stanford",
        "CALIFORNIA": "California",
        "CAL": "California",
        "COLORADO": "Colorado",
        "UTAH": "Utah",
        
        // Big East
        "VILLANOVA": "Villanova",
        "NOVA": "Villanova",
        "GEORGETOWN": "Georgetown",
        "MARQUETTE": "Marquette",
        "CREIGHTON": "Creighton",
        "XAVIER": "Xavier",
        "PROVIDENCE": "Providence",
        "ST-JOHNS": "St. John's",
        "ST-JOHNS-NY": "St. John's",
        "SETON-HALL": "Seton Hall",
        "BUTLER": "Butler",
        "DEPAUL": "DePaul",
        
        // Other Notable Teams
        "GONZAGA": "Gonzaga",
        "MEMPHIS": "Memphis",
        "HOUSTON": "Houston",
        "CONNECTICUT": "UConn",
        "UCONN": "UConn",
        
        // Additional Teams (alphabetical)
        "AKRON": "Akron",
        "ALABAMA-BIRMINGHAM": "UAB",
        "ALBANY NY": "Albany NY",
        "UAB": "UAB",
        "ARIZONA-STATE": "Arizona State",
        "ARKANSAS-STATE": "Arkansas State",
        "ARMY": "Army",
        "AUSTIN-PEAY": "Austin Peay",
        "BALL-STATE": "Ball State",
        "BELMONT": "Belmont",
        "BOISE-STATE": "Boise State",
        "BRADLEY": "Bradley",
        "BRIGHAM-YOUNG": "BYU",
        "BYU": "BYU",
        "BROWN": "Brown",
        "BUFFALO": "Buffalo",
        "CENTRAL-FLORIDA": "UCF",
        "UCF": "UCF",
        "CENTRAL-MICHIGAN": "Central Michigan",
        "CHARLESTON": "Charleston",
        "CHARLESTONSOUTHERN": "Charleston Southern",
        "CHARLOTTE": "Charlotte",
        "CINCINNATI": "Cincinnati",
        "CITADEL": "The Citadel",
        "CSUFULLERTON": "CSU Fullerton",
        "COASTAL-CAROLINA": "Coastal Carolina",
        "COLGATE": "Colgate",
        "COLORADO-STATE": "Colorado State",
        "COLUMBIA": "Columbia",
        "CORNELL": "Cornell",
        "DARTMOUTH": "Dartmouth",
        "DAVIDSON": "Davidson",
        "DAYTON": "Dayton",
        "DELAWARE": "Delaware",
        "DENVER": "Denver",
        "DETROIT": "Detroit Mercy",
        "DRAKE": "Drake",
        "DREXEL": "Drexel",
        "EAST-CAROLINA": "East Carolina",
        "EASTERN-KENTUCKY": "Eastern Kentucky",
        "EASTERN-MICHIGAN": "Eastern Michigan",
        "EVANSVILLE": "Evansville",
        "FAIRFIELD": "Fairfield",
        "FLORIDA-ATLANTIC": "Florida Atlantic",
        "FAU": "Florida Atlantic",
        "FLORIDA-GULF-COAST": "FGCU",
        "FGCU": "FGCU",
        "FORDHAM": "Fordham",
        "FRESNO-STATE": "Fresno State",
        "FURMAN": "Furman",
        "GEORGE-MASON": "George Mason",
        "GEORGE-WASHINGTON": "George Washington",
        "GEORGIA-STATE": "Georgia State",
        "GRAMBLING": "Grambling",
        "GRAND-CANYON": "Grand Canyon",
        "HARVARD": "Harvard",
        "HAWAII": "Hawaiʻi",
        "HOFSTRA": "Hofstra",
        "HOLY-CROSS": "Holy Cross",
        "IDAHO": "Idaho",
        "IDAHO-STATE": "Idaho State",
        "ILLINOIS-CHICAGO": "UIC",
        "UIC": "UIC",
        "ILLINOIS-STATE": "Illinois State",
        "INCARNATE-WORD": "Incarnate Word",
        "INDIANA-STATE": "Indiana State",
        "IONA": "Iona",
        "IUPUI": "IUPUI",
        "JACKSON-STATE": "Jackson State",
        "JACKSONVILLE": "Jacksonville",
        "JACKSONVILLE-STATE": "Jacksonville State",
        "JAMES-MADISON": "James Madison",
        "KANSAS-CITY": "Kansas City",
        "KENTSTATE": "Kent State",
        "KENNESAWSTATE": "Kennesaw State",
        "LA-SALLE": "La Salle",
        "LAFAYETTE": "Lafayette",
        "LEHIGH": "Lehigh",
        "LIBERTY": "Liberty",
        "LIPSCOMB": "Lipscomb",
        "LONG-BEACH-STATE": "Long Beach State",
        "LONGISLANDUNIVERSITY" : "Long Island University",
        "LOYOLA-CHICAGO": "Loyola Chicago",
        "LOYOLA-MARYMOUNT": "Loyola Marymount",
        "MAINE": "Maine",
        "MANHATTAN": "Manhattan",
        "MARIST": "Marist",
        "MARSHALL": "Marshall",
        "MASSACHUSETTS": "UMass",
        "UMASS": "UMass",
        "MCNEESE-STATE": "McNeese",
        "MERCER": "Mercer",
        "MIAMI-OH": "Miami (OH)",
        "MIDDLE-TENNESSEE": "Middle Tennessee",
        "MILWAUKEE": "Milwaukee",
        "MISSISSIPPI-VALLEY-STATE": "Mississippi Valley State",
        "MONMOUTH": "Monmouth",
        "MONTANA": "Montana",
        "MONTANA-STATE": "Montana State",
        "MOREHEAD-STATE": "Morehead State",
        "MURRAY-STATE": "Murray State",
        "NAVY": "Navy",
        "NEVADA": "Nevada",
        "NEW-MEXICO": "New Mexico",
        "NEW-MEXICO-STATE": "New Mexico State",
        "NEW-ORLEANS": "New Orleans",
        "NIAGARA": "Niagara",
        "NORTH-CAROLINA-AT": "NC A&T",
        "NORTH-CAROLINA-CENTRAL": "NC Central",
        "NORTH-TEXAS": "North Texas",
        "NORTHEASTERN": "Northeastern",
        "NORTHERN-ARIZONA": "Northern Arizona",
        "NORTHERN-COLORADO": "Northern Colorado",
        "NORTHERN-ILLINOIS": "Northern Illinois",
        "NORTHERN-IOWA": "Northern Iowa",
        "NORTHWESTERN-STATE": "Northwestern State",
        "OAKLAND": "Oakland",
        "OHIO": "Ohio",
        "OLD-DOMINION": "Old Dominion",
        "ORAL-ROBERTS": "Oral Roberts",
        "OREGON-STATE": "Oregon State",
        "PACIFIC": "Pacific",
        "PENNSYLVANIA": "Penn",
        "PENN": "Penn",
        "PEPPERDINE": "Pepperdine",
        "PORTLAND": "Portland",
        "PORTLAND-STATE": "Portland State",
        "PRAIRIE-VIEW": "Prairie View A&M",
        "PRINCETON": "Princeton",
        "PURDUE-FORT-WAYNE": "Purdue Fort Wayne",
        "QUINNIPIAC": "Quinnipiac",
        "RADFORD": "Radford",
        "RHODE-ISLAND": "Rhode Island",
        "RICE": "Rice",
        "RICHMOND": "Richmond",
        "RIDER": "Rider",
        "ROBERT-MORRIS": "Robert Morris",
        "SAINT-BONAVENTURE": "St. Bonaventure",
        "SAINT-JOSEPHS": "Saint Joseph's",
        "ST-JOSEPHS": "Saint Joseph's",
        "SAINT-LOUIS": "Saint Louis",
        "ST-LOUIS": "Saint Louis",
        "SAINT-MARYS": "Saint Mary's",
        "ST-MARYS": "Saint Mary's",
        "SAINT-PETERS": "Saint Peter's",
        "ST-PETERS": "Saint Peter's",
        "SAMFORD": "Samford",
        "SAN-DIEGO": "San Diego",
        "SANDIEGOSTATE": "San Diego State",
        "SAN-FRANCISCO": "San Francisco",
        "SAN-JOSE-STATE": "San José State",
        "SANTA-CLARA": "Santa Clara",
        "SEATTLE": "Seattle",
        "SIENA": "Siena",
        "SOUTH-ALABAMA": "South Alabama",
        "SOUTH-DAKOTA": "South Dakota",
        "SOUTH-DAKOTA-STATE": "South Dakota State",
        "SOUTH-FLORIDA": "South Florida",
        "USF": "South Florida",
        "SOUTHEAST-MISSOURI-STATE": "Southeast Missouri State",
        "SOUTHEASTERN-LOUISIANA": "Southeastern Louisiana",
        "SOUTHERN-ILLINOIS": "Southern Illinois",
        "SOUTHERN-METHODIST": "SMU",
        "SMU": "SMU",
        "SOUTHERN-MISSISSIPPI": "Southern Miss",
        "SOUTHERN-MISS": "Southern Miss",
        "SOUTHERN-UTAH": "Southern Utah",
        "ST-FRANCIS-NY": "St. Francis Brooklyn",
        "ST-FRANCIS-PA": "Saint Francis (PA)",
        "STEPHEN-F-AUSTIN": "SFA",
        "SFA": "SFA",
        "STETSON": "Stetson",
        "STONY-BROOK": "Stony Brook",
        "TEMPLE": "Temple",
        "TENNESSEE-STATE": "Tennessee State",
        "TENNESSEE-TECH": "Tennessee Tech",
        "TEXAS-A&M-CORPUS-CHRISTI": "Texas A&M-Corpus Christi",
        "TEXAS-ARLINGTON": "UT Arlington",
        "TEXAS-CHRISTIAN": "TCU",
        "TEXAS-EL-PASO": "UTEP",
        "UTEP": "UTEP",
        "TEXAS-SAN-ANTONIO": "UTSA",
        "UTSA": "UTSA",
        "TEXAS-SOUTHERN": "Texas Southern",
        "TEXAS-STATE": "Texas State",
        "TOLEDO": "Toledo",
        "TOWSON": "Towson",
        "TROY": "Troy",
        "TULANE": "Tulane",
        "TULSA": "Tulsa",
        "CALIFORNIA-DAVIS": "UC Davis",
        "UC-DAVIS": "UC Davis",
        "CALIFORNIA-IRVINE": "UC Irvine",
        "UC-IRVINE": "UC Irvine",
        "CALIFORNIA-RIVERSIDE": "UC Riverside",
        "UC-RIVERSIDE": "UC Riverside",
        "CALIFORNIA-SANTA-BARBARA": "UC Santa Barbara",
        "UC-SANTA-BARBARA": "UC Santa Barbara",
        "UCSB": "UC Santa Barbara",
        "UMASSLOWELL": "UMass Lowell",
        "UTAH-STATE": "Utah State",
        "UTAH-VALLEY": "Utah Valley",
        "VALPARAISO": "Valparaiso",
        "VERMONT": "Vermont",
        "VIRGINIA-MILITARY-INSTITUTE": "VMI",
        "VMI": "VMI",
        "WICHITA-STATE": "Wichita State",
        "WILLIAM-MARY": "William & Mary",
        "WINTHROP": "Winthrop",
        "GREENBAY": "Green Bay",
        "WISCONSIN-MILWAUKEE": "Milwaukee",
        "WOFFORD": "Wofford",
        "WRIGHT-STATE": "Wright State",
        "WYOMING": "Wyoming",
        "YALE": "Yale",
        "YOUNGSTOWN-STATE": "Youngstown State"
    ]
}

// MARK: - Extensions
extension String {
    /// Converts a display format team name to Firebase format (uppercase with hyphens)
    /// Example: "North Carolina" -> "NORTH-CAROLINA"
    var toFirebaseFormat: String {
        // First check if we have a reverse mapping
        for (key, value) in TeamNameFormatter.teamMapping {
            if value == self {
                return key
            }
        }
        
        // Otherwise format based on conventions
        return self.uppercased().replacingOccurrences(of: " ", with: "-")
    }
}
